// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onFeedTimeChange();
void onFoodIsEmptyChange();
void onIsCatChange();
void onLocalTimeChange();

CloudMotionSensor motionDetected;
CloudSchedule feedTime;
bool foodIsEmpty;
bool isCat;
CloudTime localTime;

void initProperties(){

  ArduinoCloud.addProperty(motionDetected, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(feedTime, READWRITE, ON_CHANGE, onFeedTimeChange);
  ArduinoCloud.addProperty(foodIsEmpty, READWRITE, ON_CHANGE, onFoodIsEmptyChange);
  ArduinoCloud.addProperty(isCat, READWRITE, ON_CHANGE, onIsCatChange);
  ArduinoCloud.addProperty(localTime, READWRITE, 30 * SECONDS, onLocalTimeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
